config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :bookings, only:[:new, :create, :show, :edit, :update] do
    member do
      get 'traveller' , to: "bookings#traveller"
      get 'confirmation', to: "bookings#confirmation", as: "confirmation"
    end
  end

#maybe payment needs to be nested above
  resources :bookings, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  get "/coming-soon", to: "pages#coming_soon", as: "coming_soon"


end

app/models/booking.rb
class Booking < ApplicationRecord
  # validates :origin, presence: true
  validates :budget_pp, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 150, less_than_or_equal_to: 1000 }
  validates :climate, presence: true, inclusion: { in: %w(warm cold surprise),
    message: "%{value} is not a valid climate" }
  validates :accommodation_type, presence: true, inclusion: { in: ["Hostel", "Hotel", "Bed and Breakfast", "Luxury Hotel"]}
  validates :type_id, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 4 }
  validates :number_traveller, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 6 }
  validates :start_time, presence: true
  validate :start_time_cannot_be_in_the_past


  has_many :travellers
  belongs_to :package, required: false
  belongs_to :user, required: false
  belongs_to :type, required: false
  accepts_nested_attributes_for :travellers


  monetize :price_cents

  # after_create :new_traveller

  def new_traveller
    traveller = Traveller.new
    traveller.booking = self
    traveller.save
  end

  def new_traveller_first(name)
    traveller = Traveller.new(first_name: name)
    traveller.booking = self
    traveller.save
  end


  def set_price
    self.price_cents = ( self.budget_pp * self.number_traveller * 100 )
    self.save
  end

  def match_to_package
    packages = Package.all
    if self.climate != "surprise"
      packages = packages.select {|pack| (pack.climate == self.climate) }
    end
    if self.type_id != 4
      packages = packages.select {|pack| (pack.type_id == self.type_id) }
    end
    self.package = packages.sample
  end


  private
    def start_time_cannot_be_in_the_past
      errors.add(:start_time, "can't be in the past") if
        !start_time.blank? and start_time < Date.today
    end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create, :traveller, :update]
  before_action :set_booking, only: [:show, :edit, :update, :traveller]

  def new
    @booking = Booking.new
    @types = Type.all

    @user = current_user
  end

  def create
    @booking = Booking.new(booking_params)
    if (params[:booking]["start_date"] && params[:booking]["start_time"] && params[:booking]["start_date"] != "")
      @booking.start_time = DateTime.parse("#{params[:booking]["start_date"]} #{params[:booking]["start_time"]}")
    end
    @booking.budget_pp = params[:budget_pp].to_i
    @booking.set_price

    @booking.match_to_package

    counter = 0
    @booking.number_traveller.times do
      if counter == 0
      @booking.new_traveller_first(params["first_name"])
      else
      @booking.new_traveller
      end
      counter += 1
    end
    @booking.user = current_user
    @booking.save
    unless current_user
      session[:last_booking_id] = @booking.id
    end
    if @booking.save

      flash[:alert].clear if flash[:alert]
      redirect_to traveller_booking_path(@booking)
    else
      flash.now[:alert] = @booking.errors.full_messages.join(", ")
      render :new
    end

  end

  def edit
  end

  def update
    @booking.travellers.each_with_index do |traveller, index|
      traveller.update(traveller_params(index))
    end
    if @booking.travellers.any?{|t| t.errors.messages != {} }
       flash.now[:alert] = @booking.travellers.map {|t| t.errors.full_messages}.flatten.join(", ")
       render :traveller
    else
      flash[:alert].clear if flash[:alert]
      redirect_to booking_path(@booking)
    end
  end

  def show
    if session[:last_booking_id]
      @booking.user = current_user
      @booking.save!
    end

  end

  def traveller
  end

  def confirmation
    booking = Booking.find(params[:id])
    sms = TwilioService.new(booking.user.phone)
    weather = WheatherService.new(Booking.find(params[:id]).package).get_weather

    weather_text = "Hi #{booking.travellers[0].first_name}, your trip is just 5 days away! As a little headsup, your weather will be #{weather.description}. You are expected to have #{weather.expected_temp}°C and #{weather.humidity}% humidity."
    sms.weather(weather_text)
    sms.confirmation(booking.travellers[0])
    sms.reveal(booking)

  end

  private
  def set_booking
    @booking = Booking.find(params[:id])
  end

  # set params for booking

  def booking_params
    params.require(:booking).permit(:origin, :number_traveller, :type_id, :climate, :accommodation_type)
  end

  def traveller_params(traveller_index)
    params.require("traveller_#{traveller_index}".to_sym).permit(:title, :first_name, :last_name, :nationality, :birth_date, :passport_number, :passport_expiration)
  end
end

app/views/bookings/_backup.html.erb
<div class="summary-container--grid">
    <div class="grid-image-left">
      <div class="image-summary-booking">
      </div>
    </div>
    <div class="grid-summary-general-heading">
      <span>hello</span>
    </div>
    <div class="grid-submit-button">
      <br>
      <%= form_tag booking_payments_path(@booking) do %>


        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-name="My Teddy"
          data-email="<%= current_user.email %>"
          data-amount="<%= @booking.price_cents %>"
          data-currency= eur ></script>
      <% end %>

    </div>

    <%= render '/shared/cards_summary_booking/first_card', booking: @booking %>
    <%= render '/shared/cards_summary_booking/second_card', booking: @booking %>
    <%= render '/shared/cards_summary_booking/third_card', booking: @booking %>
  </div>

app/views/bookings/confirm.html.erb
<h1>Bookings#confirm</h1>
<p>Find me in app/views/bookings/confirm.html.erb</p>

app/views/bookings/confirmation.html.erb
<div class="confirmation">
  <section class="kitty">
    <h1 id="omg" class="text-center">Your trip to DESTINATION UNKNOWN is booked!</h1>
  </section>
  <div class="text-container">
    <section id="left" class="half left">
      <h1>I've got a surprise for you</h1>
    </section>
    <section id="right" class="half right">
      <h1>I've got a surprise for you</h1>
    </section>
    <button class="btn" id="btn">+</button>
  </div>
</div>

app/views/bookings/congratulation.html.erb
<h1>Bookings#congratulation</h1>
<p>Find me in app/views/bookings/congratulation.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

<p>exactly the same page as the new booking</p>

 <p>this updates and adds the user to to the booking</p>
 <%= link_to "Review your input", booking_path(@booking), method: :patch, class: "btn btn-primary btn-lg" %>


  <%= link_to "Back to Home", root_path, class: "btn btn-primary btn-lg" %>

app/views/bookings/new.html.erb
<%= render '/shared/banners/banner_booking_new' %>

<form action="<%= bookings_path(@booking) %>" method="post">

  <input name="authenticity_token" value="<%=form_authenticity_token %>" type="hidden">

  <%= render '/shared/navbar_side' %>

  <%= render '/shared/index_cards_booking/first_card' %>
  <%= render '/shared/index_cards_booking/second_card' %>
  <%= render '/shared/index_cards_booking/third_card' %>
  <%= render '/shared/index_cards_booking/fourth_card' %>
  <%= render '/shared/index_cards_booking/fifth_card' %>

</form>

app/views/bookings/show.html.erb
<div class="sum-container">
  <div class="sum-booking">
    <div class="information-wrapper">

      <div class="heading-span">
        <span>Trip Summary</span>
      </div>



      <div class="trip-details-sum">
        <div class="trip--details">
          <div class="trip-headings-spans">
            <span >Trip Details</span>
          </div>
          <span id="traveller_info" style="display: inline-block; width: 200px;" > Number of Travellers: </span>
            <span id="user_info"=> <%= @booking.number_traveller  %> </span><br>

          <span id="traveller_info" style="display: inline-block; width: 200px;">Origin:</span>
            <span class="text-left" id="user_info"=> <%= @booking.origin %></span><br>

          <span id="traveller_info" style="display: inline-block; width: 200px;">Departure:</span>
            <span  class="text-left" id="user_info"=> <%= @booking.start_time.strftime("%d.%m.%Y")%>  after <%= @booking.start_time.strftime("%l %p")%> </span><br>

          <span id="traveller_info" style="display: inline-block; width: 200px;">Climate:</span>
            <span class="text-left"  id="user_info"=><%= @booking.climate %> </span><br>

          <span id="traveller_info" style="display: inline-block; width: 200px;">Type:</span>
          <span class="text-left"  id="user_info"=><%= @booking.type.name %> </span><br>

          <span id="traveller_info" style="display: inline-block; width: 200px;">Accomodation type:</span>
            <span class="text-left" id="user_info"=> <%= @booking.accommodation_type %> </span><br>

          <span id="traveller_info" style="display: inline-block; width: 200px;">Excluded countries:</span>
            <span class="text-left" id="user_info"=>Germany<%= @booking.excluded_countries %></span><br>
        </div>

        <hr>

        <div class="trip--personal">
          <div class="trip-headings-spans">
            <span >Personal Details</span>
          </div>

          <span id="traveller_info" style="display: inline-block; width: 200px;">Name: </span>
            <span id="user_info"> <%= @booking.travellers.first.first_name + ' ' + @booking.travellers.first.last_name %> </span><br>

          <span id="traveller_info" style="display: inline-block; width: 200px;">Email: </span>
            <span id="user_info"=><%= current_user.email %> </span><br>
          <span id="traveller_info" style="display: inline-block; width: 200px;">Phone: </span>
            <span id="user_info"=><%= current_user.phone %> </span><br>
          <div class="popup-container flex">
            <div class="row">
              <% @booking.travellers.each_with_index do |traveller,index| %>
              <div class="col-xs-6 col-md-6 ">
                <div class="box"> <a class="button" href="#popup<%= index %>"><%= traveller.first_name + ' ' + traveller.last_name  %></a>
                </div>
                </div>
                <div id="popup<%= index %>" class="overlay">
                  <div class="popup">
                   <span class="center-heading">TRAVELLER DETAILS </span>
                   <a class="close" href="#modal-anchor">&times;</a>
                   <span  id="traveller_info" style="display: inline-block; width: 200px; margin-top: 2%;">Name:</span>
                    <span id="user_info"=><%= traveller.first_name + ' ' + traveller.last_name %></span><br>
                   <span  id="traveller_info" style="display: inline-block; width: 200px;margin-top: 2%;">Birthday:</span>
                    <span id="user_info"=><%= traveller.birth_date %></span><br>
                   <span id="traveller_info" style="display: inline-block; width: 200px;margin-top: 2%;">Passport Number: </span>
                    <span id="user_info"=><%= traveller.passport_number %></span><br>
                   <span id="traveller_info" style="display: inline-block; width: 200px;margin-top: 2%;"> Nationality: </span>
                    <span id="user_info"=><%= traveller.nationality %></span><br>
                   <span id="traveller_info" style="display: inline-block; width: 200px;margin-top: 2%;">Expiry Date:</span>
                    <span id="user_info"=><%= traveller.passport_expiration %></span><br>

                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>

        <hr>

        <div class="trip--payment">
          <div class="trip-headings-spans">
            <span>Payment</span>
          </div>
          <span id="traveller_info" style="display: inline-block; width: 200px;">Budget per Person: </span>
            <span id="user_info"=> €<%= @booking.budget_pp  %> </span><br>
          <span id="traveller_info" style="display: inline-block; width: 200px;">Number of Travellers: </span>
            <span id="user_info"=> <%= @booking.number_traveller %></span><br>

          <span  style="display: inline-block; width: 200px;"> Total Amount: </span> <span><%= humanized_money_with_symbol(@booking.price) %> </span><br>
        </div>
      </div>

      <div class="pay-now">
        <%= form_tag booking_payments_path(@booking) do %>
          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-name="Pay your Trip"
            data-email="<%= current_user.email %>"
            data-amount="<%= @booking.price_cents %>"
            data-currency= eur ></script>
            <script>
        // Hide default stripe button, be careful there if you
        // have more than 1 button of that class
        document.getElementsByClassName("stripe-button-el")[0].style.display = 'none';
    </script>
            <button type="submit" class="yourcustomclass margin-top--pay">Pay Now</button>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/bookings/traveller.html.erb
<form action="<%= booking_path(@booking) %>" method="POST">
  <input type="hidden" name="_method" value="patch">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

    <%= render '/shared/banners/banner_booking_2' %>

    <%= render '/shared/update_cards_booking/personal_details' %>
</form>