config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :bookings, only:[:new, :create, :show, :edit, :update] do
    member do
      get 'traveller' , to: "bookings#traveller"
      get 'confirmation', to: "bookings#confirmation", as: "confirmation"
    end
  end

#maybe payment needs to be nested above
  resources :bookings, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  get "/coming-soon", to: "pages#coming_soon", as: "coming_soon"


end

app/views/shared/_booking_summary.html.erb
<div class="summary-container">
  <div class="summary-container--grid">
    <div class="grid-image-left">
      <div class="image-summary-booking">
      </div>
    </div>
    <div class="grid-summary-general-heading">
      <span>Summary of your trip</span>
    </div>



  </div>
</div>

app/views/shared/_error_messages.html.erb
_error_messages.html.erb

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <%= link_to "", coming_soon_path, class: "fab fa-instagram" %>
    <%= link_to "", coming_soon_path, class: "fab fa-facebook" %>
    <%= link_to "", coming_soon_path, class: "fab fa-twitter" %>
    <%= link_to "", coming_soon_path, class: "fab fa-linkedin" %>
  </div>


  <div class="footer-links terms-conditions">
        <%= link_to "Terms and Conditions", coming_soon_path%>
  </div>

  <div class="footer-links footer-copyright">
      <%= link_to "TrvlScape", root_path%>

  </div>
</div>

app/views/shared/_how_it_works.html.erb
<div class="hiw">
  <h2>TRVLSCAPE<span class="point-orange">.</span></h2>
  <h3>Because life is either a daring adventure or nothing at all</h3>

  <div class="card-how-to--left-top">
    <div class="row">
      <div class="col-sm-5 col-xs-12">
        <div class="index-number" id="hiw-destination-unknown-number">
          <h5>1</h5>
          <div class="card-image" id="hiw-destination-unknown">
          </div>
        </div>
      </div>
      <div class="col-sm-7 col-xs-12">
        <div class="card-text">
          <div>
            <h1>Engineer the Unknown </h1>
            <p>Book a 3 day trip to a destination unknown. Take 4 minutes to tell us about your preferences and your budget and we tailor your surprise trip. We book your flight and a hotel for 3 days.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

<div class="card-how-to--right">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <div class="card-text">
          <div>
            <h1 class="text-right">Embrace the Unpredictable</h1>
            <p class="text-right">Going to a relaxing beach, living in an iglo in Greenland or sleeping in a hammock in the Jungle. Everything is possible and you don't have to lift a finger. </p>
          </div>
        </div>
      </div>
      <div class="col-sm-5 col-xs-12">
        <div class="index-number" id="hiw-relax-number">
          <div class="card-image" id="hiw-relax">
          </div>
          <h5>2</h5>
        </div>
      </div>
    </div>
  </div>


<div class="card-how-to--left-bottom">
    <div class="row">
      <div class="col-sm-5 col-xs-12">
        <div class="index-number" id="hiw-trip-number">
          <h5>3</h5>
          <div class="card-image" id="hiw-trip">
          </div>
        </div>
      </div>
      <div class="col-sm-7 col-xs-12">
        <div class="card-text">
          <div>
            <h1>Start your Surprise Trip</h1>
            <p>Experience your vacation in the thrill of the unknown. 5 Days before your trip we will send you a wheather report. 3 Days before some hints on what to pack. Only of the day of your flight you will be told the destination.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-lp">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <span class="name-logo">TRVELSCAPE</span>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->

      <div class="booknow">
          <%= link_to "Book Now!", "bookings/new", class: "navbar-wagon-item navbar-wagon-link" %>
      </div>

      <!-- Avatar with dropdown menu -->
     <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "paper-plane.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= image_tag "paper-plane.png", class: "avatar", id: "navbar-wagon-menu"%>
    <% end %>
  </div>
</div>

app/views/shared/_navbar_side.html.erb
<div class="nav-side">
  <a href="#first-step">
    <div class="nav-side-step">
      <div class="nav-side-step-text">Your Travel</div>
      <div class="nav-side-step-num num1">1</div>
    </div>
  </a>
  <a href="#second-step">
    <div class="nav-side-step">
      <div class="nav-side-step-text">Origin</div>
      <div class="nav-side-step-num">2</div>
    </div>
  </a>
  <a href="#third-step">
    <div class="nav-side-step">
      <div class="nav-side-step-text ">Travellers</div>
      <div class="nav-side-step-num ">3</div>
    </div>
  </a>
  <a href="#modal-anchor">
    <div class="nav-side-step">
      <div class="nav-side-step-text ">Preferences</div>
      <div class="nav-side-step-num ">4</div>
    </div>
  </a>
  <a href="#fith-step">
    <div class="nav-side-step">
      <div class="nav-side-step-text ">Budget</div>
      <div class="nav-side-step-num ">5</div>
    </div>
  </a>
</div>

app/views/shared/_svens_code.html.erb
<h1>Show page of a booking</h1>

<h2>Your Booking</h2>
<p>Type of Travel: <%=@booking.type.name  %></p>
<p>Depature: <%=@booking.start_date %></p>
<p>Depaturing after: <%= @booking.start_time.strftime('%H')  %>pm</p>
<p>Your Destination will be: <%=@booking.climate  %></p>

<%=@booking.number_traveller  %>
<% @booking.travellers.each do |traveller|  %>
<p> Name: <%= traveller.first_name  %> <%= traveller.last_name  %> </p>
<p>Passport-num:  <%= traveller.passport_number  %></p>
<% end %>

  <%= link_to "Edit booking details", edit_booking_path(@booking), class: "btn btn-primary btn-lg" %>
  <%= link_to "Edit Traveller details", traveller_booking_path(@booking), class: "btn btn-primary btn-lg" %>

app/views/shared/_testimonials.html.erb
<div class="testimonials">

  <h2>TESTIMONIALS<span class="point-orange">.</span></h2>
  <h3>These people had a blast</h3>


  <div class="row">

    <div class="col-xs-12 col-sm-4">
        <div class="card" >
         <div class="card-testimonial card-testimonial"
         style="background-image: linear-gradient(-225deg, rgba(30,30,30,0.4) 0%, rgba(30,30,30,0.1) 50%), url(<%= image_path('testemonials_Koblenz.jpg') %>)">
          <div class="card-description--yellow"
            data-hover="'Before the trip I never heard of Koblenz. However it was overwhelming: A beautiful city and landscape at the river Rhine!' - Piotr">
            <p> KOBLENZ </p>
          </div>
        </div>
       </div>

    </div>

    <div class="col-xs-12 col-sm-4">
      <div class="card" >
       <div class="card-testimonial card-testimonial" style="background-image:linear-gradient(-225deg, rgba(30,30,30,0.4) 0%, rgba(30,30,30,0.1) 50%),  url(<%= image_path('testemonials_Reykjavik.jpg') %>)">
        <div class="card-description--blue"
          data-hover="'Iceland had been on my list for a long time! TrvlScape finally got me there. Send nudes ;-) ' - Charly">
          <p> REYKJAVIK </p>
         </div>
       </div>
      </div>

    </div>

    <div class="col-xs-12 col-sm-4">
      <div class="card" >
       <div class="card-testimonial card-testimonial" style="background-image:linear-gradient(-225deg, rgba(30,30,30,0.4) 0%, rgba(30,30,30,0.1) 50%),  url(<%= image_path('testemonials_Cappadocia.jpg') %>)">
       <div class="card-description--red"
        data-hover="'I choose the adventure trip: Seeing the beautiful sunrise and the ballons after an amazing hike were astonishing!'- Willy  ">
        <p> CAPPADOCIA </p>

       </div>
      </div>
     </div>

    </div>

  </div>
 </div>
</div>